name: Deploy Dev (Custom Action)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: miketheodorou/release-action@v1.0.3
        with:
          deployment-owner: miketheodorou
          deployment-repo: ci-env-dev
          project-owner: miketheodorou
          project-repo: ci-workflow-poc
          github-token: ${{ secrets.PAT }}
