name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev
          - qa
          - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2

      - name: Get Latest Release
        uses: actions/github-script@v5
        id: latest_release
        with:
          script: |
            const { getLatestRelease } = require(`${process.env.GITHUB_WORKSPACE}/ci/index.js`);
            const { name, tag_name, html_url } = await getLatestRelease({ github, owner: 'miketheo423', repo: 'ci-workflow-poc' });

            core.setOutput('name', name);
            core.setOutput('tag_name', tag_name);
            core.setOutput('html_url', html_url);

      - name: Update values.yml
        uses: actions/github-script@v5
        env:
          REPO: ci-env-${{ github.event.inputs.environment }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          VERSION: "${{ steps.latest_release.outputs.tag_name }}"
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { getValuesFile, updateVersionInFile, updateValuesFile } = require(`${process.env.GITHUB_WORKSPACE}/ci/index.js`);

            const { ENVIRONMENT, VERSION, REPO } = process.env;
            const owner = 'miketheo423';
            const path = 'values.yaml';

            const { content, sha } = await getValuesFile({ github, owner, repo: REPO, path })

            const updatedContent = updateVersionInFile(content, VERSION);

            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo: REPO,
              path,
              content: updatedContent,
              sha,
              message: `Bumps to ${VERSION}`,
              committer: {
                name: context.actor,
                email: 'miketheocodes@gmail.com'
              },
              author: {
                name: context.actor,
                email: 'miketheocodes@gmail.com'
              }
            });

      - name: Checkout Deployment Repo
        uses: actions/checkout@v2
        with:
          repository: "miketheo423/ci-env-${{ github.event.inputs.environment }}"
          ref: main
          token: ${{ secrets.PAT }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          release_name: ${{ steps.picks_release.outputs.name }}
          tag_name: ${{ steps.latest_release.outputs.tag_name }}
          commitish: ${{ github.ref }}
          body: |
            Release Notes:
            ${{ steps.latest_release.outputs.html_url }}
          draft: false
          prerelease: false
          owner: miketheo423
          repo: ci-env-${{ github.event.inputs.environment }}
