name: Deploy to Environment

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev
          - qa
          - stage

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of Predict
        uses: rez0n/actions-github-release@main
        id: picks_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "miketheo423/ci-workflow-poc"
          type: "stable"
      - name: Show release version
        run: |
          echo ${{ steps.picks_release.outputs.release }} \
          echo ${{ steps.picks_release.outputs.release_id }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.picks_release.outputs.release }}
          release_name: Release ${{ steps.picks_release.outputs.release }}
          body: |
            Release Notes:
            https://github.com/miketheo423/ci-workflow-poc/releases/tag/${{ steps.picks_release.outputs.release }}
          draft: false
          prerelease: false
          owner: miketheo423
          repo: ci-env-${{ github.event.inputs.environment }}
